[package]
name = "gf2_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
bzip2 = "0.4"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
ipnet = "2"
rhai = "1.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

